baseURL = 'https://nikeasyanzi.github.io/'
#languageCode = 'zh-TW'
languageCode = 'en-us'
title = "Craig Yang's Dev Blog"
#theme = "PaperMod"
theme = 'ananke'
languageName = "English"
paginate = 100
enableRobotsTXT = true
defaultTheme = "dark"
